#!/usr/bin/zsh
alias sudo='sudo '
alias ls='ls -F --color=auto --group-directories-first'
alias la='ls -F -A --color=auto --group-directories-first'
alias ll='ls -lhF --color=auto --group-directories-first'
alias lla='ls -lhF -A --color=auto --group-directories-first'
alias ip='ip --color=auto'
alias mkdir='mkdir -p'
alias rm='rm -r'
alias cp='cp -r'
alias tr="trash"
alias trl="trash-list | bat --style numbers,grid"
alias trr="trash-restore"
alias se='sudo -e'
alias sc='sudo --preserve-env=WAYLAND_DISPLAY,XDG_RUNTIME_DIR'
alias sec='sudo -e --preserve-env=WAYLAND_DISPLAY,XDG_RUNTIME_DIR'

autoload -Uz run-help
(( ${+aliases[run-help]} )) && unalias run-help
alias help='run-help'
autoload -Uz run-help-git run-help-ip \
    run-help-openssl run-help-p4 run-help-sudo \
    run-help-svk run-help-svn run-help-btrfs

alias df="duf"
alias du="dust"
alias eik="edit-in-kitty"
alias s="kitty +kitten ssh"
alias icat="kitty +kitten icat"
alias kdiff="kitty +kitten diff"
alias pf="pkgfile"
alias pm="pacman"
alias ctl="systemctl"

alias g="git"
alias zp="z $HOME/dm/pj"
alias cf="yadm"
alias cfg="e $XDG_CONFIG_HOME/git/config"
alias cfz="e $XDG_CONFIG_HOME/zsh/.zshrc"
alias cfzp="e $XDG_CONFIG_HOME/zsh/.zprofile"
alias cfze="e $XDG_CONFIG_HOME/zsh/.zshenv"
alias cfzh="e $XDG_CONFIG_HOME/zsh/hookrc"
alias cfza="e $XDG_CONFIG_HOME/zsh/aliasrc"
alias cfzf="e $XDG_CONFIG_HOME/zsh/functionrc"
alias cfze="e $XDG_CONFIG_HOME/zsh/.zshenv"
alias cfv="e $XDG_CONFIG_HOME/nvim/init.lua"
alias cfvp="e $XDG_CONFIG_HOME/nvim/lua/plugins.lua"
alias cfl="e $XDG_CONFIG_HOME/lf/lfrc"
alias cfk="e $XDG_CONFIG_HOME/kitty/kitty.conf"
alias cfs="e $XDG_CONFIG_HOME/sway/config"
alias cfm="e $XDG_CONFIG_HOME/mpv"

alias mod="stat -c %a"
alias ar="aria2c"
alias yd="yt-dlp"
alias fm="lf"

alias zpj="z $HOME/dm/pj"
alias pj="fm $HOME/dm/pj"
alias zwd="z $XDG_DATA_HOME/windows"
alias wd="fm $XDG_DATA_HOME/windows"
alias zvd="z $HOME/vd"
alias vd="fm $HOME/vd"
alias ani="fm $HOME/vd/anime/."
alias zpt="z $HOME/pt"
alias pt="fm $HOME/pt"
alias zdl="z $HOME/dl"
alias dl="fm $HOME/dl"
alias zdm="z $HOME/dm"
alias dm="fm $HOME/dm"
alias zdt="z $HOME/dt"
alias dt="fm $HOME/dt"
alias zms="z $HOME/ms"
alias ms="fm $HOME/ms"
alias ztl="z $HOME/dl/Telegram\ Desktop"
alias tl="fm $HOME/dl/Telegram\ Desktop"
alias zstm="z $HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam"

alias startsway="env __GL_GSYNC_ALLOWED=0 __GL_VRR_ALLOWED=0 WLR_DRM_NO_ATOMIC=1 XDG_CURRENT_DESKTOP=sway WLR_NO_HARDWARE_CURSORS=1 MOZ_ENABLE_WAYLAND=1 sway --unsupported-gpu"

alias rcow="fortune -c | cowthink -f $(find /usr/share/cows -type f | shuf -n 1)"
alias rpony="fortune -c | ponythink -f $(find /usr/share/ponysay/ponies -type f | shuf -n 1)"
