#!/usr/bin/zsh
alias sudo='sudo '
alias ls='ls -F --color=auto --group-directories-first'
alias la='ls -F -A --color=auto --group-directories-first'
alias ll='ls -lhF --color=auto --group-directories-first'
alias lla='ls -lhF -A --color=auto --group-directories-first'
alias ip='ip --color=auto'
alias e='nvim'
alias se='sudoedit'

autoload -Uz run-help
(( ${+aliases[run-help]} )) && unalias run-help
alias help='run-help'
autoload -Uz run-help-git run-help-ip \
    run-help-openssl run-help-p4 run-help-sudo \
    run-help-svk run-help-svn run-help-btrfs

alias df="duf"
alias du="dust"
alias eik="edit-in-kitty"
alias d="nvim -d"
alias ra="ranger"
alias mod="stat -c %a"
alias pf="pkgfile"

alias g="git"
alias zg="z $HOME/dev/git"
#alias cf="g --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME"
alias cf="yadm --yadm-repo $HOME/.config/dotfiles --work-tree=$HOME"
alias cfz="e $HOME/.config/zsh/.zshrc"
alias cfzp="e $HOME/.config/zsh/.zprofile"
alias cfa="e $HOME/.config/zsh/aliasrc"
alias cff="e $HOME/.config/zsh/functionrc"
alias cfe="e $HOME/.config/zsh/.zshenv"
alias cfv="e $HOME/.config/nvim/init.lua"

alias zvd="z $HOME/vd"
alias vd="ra $HOME/vd"
alias ani="ra $HOME/vd/anime"
alias zpt="ra $HOME/pt"
alias pt="ra $HOME/pt"
alias zdl="z $HOME/dl"
alias dl="ra $HOME/dl"
alias zdm="z $HOME/dm"
alias dm="ra $HOME/dm"
alias zdt="z $HOME/dt"
alias dt="ra $HOME/dt"
alias zms="z $HOME/ms"
alias ms="ra $HOME/ms"
