#!/usr/bin/zsh
alias sudo='sudo '
alias ls='lsd --group-directories-first'
alias la='lsd -A --group-directories-first'
alias ll='command ls -lhF --color=auto --group-directories-first'
alias lla='command ls -lhF -A --color=auto --group-directories-first'
alias ip='ip --color=auto'
alias mkdir='mkdir -p'
alias rm='rm -r'
alias cp='cp -r'
alias tr="trash"
alias trl="trash-list | bat --style numbers,grid"
alias trr="trash-restore"
alias se='sudo -e'
alias sc='sudo --preserve-env=WAYLAND_DISPLAY,XDG_RUNTIME_DIR'
alias sec='sudo -e --preserve-env=WAYLAND_DISPLAY,XDG_RUNTIME_DIR'

alias log="command log"

autoload -Uz run-help
(( ${+aliases[run-help]} )) && unalias run-help
alias help='run-help'
autoload -Uz run-help-git run-help-ip \
    run-help-openssl run-help-p4 run-help-sudo \
    run-help-svk run-help-svn run-help-btrfs

alias df="duf"
alias du="dust"
alias eik="edit-in-kitty"
alias pf="pkgfile"
alias pm="pacman"
alias ctl="systemctl"

alias zp="z $HOME/dm/pj"
alias cf="yadm"
alias cfg="e $XDG_CONFIG_HOME/git/config"
alias cfz="e $XDG_CONFIG_HOME/zsh/.zshrc"
alias cfzp="e $XDG_CONFIG_HOME/zsh/.zprofile"
alias cfze="e $XDG_CONFIG_HOME/zsh/.zshenv"
alias cfzh="e $XDG_CONFIG_HOME/zsh/hookrc"
alias cfza="e $XDG_CONFIG_HOME/zsh/aliasrc"
alias cfzf="e $XDG_CONFIG_HOME/zsh/functionrc"
alias cfze="e $XDG_CONFIG_HOME/zsh/.zshenv"
alias cfv="e $XDG_CONFIG_HOME/nvim/init.lua"

alias mod="stat -c %a"

alias zvd="z $HOME/vd"
alias zdl="z $HOME/dl"
alias zdm="z $HOME/dm"
alias zdt="z $HOME/dt"
alias zms="z $HOME/ms"
