#!/usr/bin/zsh

# Replace diff with git diff
function diff() {
    command git diff --no-index "$1" "$2"
    return 0
}

function private_mode() {
    unset HISTFILE
    printf "zsh is running in private mode, history will not be persisted.\n"
}
bindkey -s '^[p' 'private_mode\n'
