#!/usr/bin/zsh

# yt-dlp audio with search
function yta() {
    command mpv --profile=audio --ytdl-format=bestaudio ytdl://ytsearch:"$*"
}

# Replace diff with git diff
function diff() {
    command git diff --no-index "$1" "$2"
    return 0
}

function private_mode() {
    unset HISTFILE
    printf "zsh is running in private mode, history will not be persisted.\n"
}
bindkey -s '^[p' 'private_mode\n'

function lfz() {
    local -r tmp="$(mktemp -t lfz.XXXXXXXXXX)"
    command lf -last-dir-path="${tmp}" "$@"
    if [[ -f "${tmp}" ]]; then
        local -r dir="$(cat "${tmp}")"
        /usr/bin/rm "${tmp}"
        if [[ -d "${dir}" ]]; then
            if [[ "${dir}" != "$(pwd)" ]]; then
                z "${dir}"
            else
                return 0
            fi
        else
            return 0
        fi
    else
        return 0
    fi
}
bindkey -s '^[m' '^ulfz\n'

# from "$(pyenv init -)", excluding the slow `rehash`
function pyenv() {
    local command
    command="${1:-}"
    if [ "$#" -gt 0 ]; then
        shift
    fi

    case "$command" in
        rehash|shell)
            eval "$(pyenv "sh-$command" "$@")"
            ;;
        *)
            command pyenv "$command" "$@"
            ;;
    esac
}
