#!/usr/bin/zsh

# Set env for some directories
function env_on_chdir {
    if [[ "${PWD}" == "${HOME}" ]]; then
        export GIT_DIR="${XDG_DATA_HOME}/yadm/repo.git"
        # GIT_WORK_TREE must be set on server, I don't know why
        export GIT_WORK_TREE="${HOME}"
    else
        unset GIT_DIR
        unset GIT_WORK_TREE
    fi
}
add-zsh-hook -Uz chpwd() {env_on_chdir}
