#!/usr/bin/zsh

#-----Git-------------
#---------------------
_set_git_env() {
    set_dir() {
        if [[ -v GIT_DIR ]]; then
            if [[ "${GIT_DIR}" != "${XDG_DATA_HOME}/yadm/repo.git" ]]; then
                export GIT_DIR="${XDG_DATA_HOME}/yadm/repo.git"
                unset -f set_dir
            else
                unset -f set_dir
            fi
        else
            export GIT_DIR="${XDG_DATA_HOME}/yadm/repo.git"
            unset -f set_dir
        fi
    }

    set_dir
}

_clr_git_env() {
    clr_dir() {
        if [[ -v GIT_DIR ]]; then
            if [[ "${GIT_DIR}" == "${XDG_DATA_HOME}/yadm/repo.git" ]]; then
                unset GIT_DIR
                unset -f clr_dir
            else
                unset -f clr_dir
            fi
        else
            unset -f clr_dir
        fi
    }

    clr_dir
}

_git_pre_exec() {
    typeset -A git_cmds=(
        g true
        git true
        gs true
    )
    typeset -A options=(
        cl true
        clone true
    )

    # There is no consistent, convenient and reliable way
    # to convert strings to lists in bash or zsh
    local cmd=${1%% *} # $1 here would be treated as a complete command string
    local remainder="${1#* }"
    local option="${remainder%% *}"

    if [[ -n "${cmd}" && -v git_cmds["${cmd}"] && "${git_cmds[$cmd]}" == true ]] || [[ "${cmd}" == 'git-'* ]]; then
        if [[ "$(pwd)" == "${HOME}" ]]; then
            if [[ -v option ]]; then
                if [[ -v options["${option}"] && "${options[$option]}" == true ]]; then
                    _clr_git_env
                else
                    _set_git_env
                fi
            else
                _set_git_env
            fi
        else
            _clr_git_env
        fi
    else
        _clr_git_env
    fi
}
preexec_functions+=(_git_pre_exec)

# Set env for some directories
# Make git completion work at HOME
_git_env_on_chdir() {
    # Set GIT_DIR and GIT_WORK_TREE when at HOME
    if [[ "$(pwd)" == "${HOME}" ]]; then
        _set_git_env
    else
        _clr_git_env
    fi
}
precmd_functions+=(_git_env_on_chdir)

#------Python venv---------
#---------------------
_auto_python_venv() {
    if [[ -n "${VIRTUAL_ENV}" && "$(pwd)" != "$VIRTUAL_ENV"* ]]; then
        deactivate
    fi
    if [[ -z "$VIRTUAL_ENV" && -f "$(pwd)/.venv/bin/activate" ]]; then
        source "$(pwd)/.venv/bin/activate"
    fi
}
chpwd_functions+=_auto_python_venv
