#!/usr/bin/zsh

# Set env for some directories
function env_on_chdir {
    # Set GIT_DIR and GIT_WORK_TREE when at HOME
    # An known issue: Can't use 'git clone' when at HOME
    # ERROR message:
    # fatal: working tree '/home/user' already exists
    if [[ "${PWD}" == "${HOME}" ]]; then
        export GIT_DIR="${XDG_DATA_HOME}/yadm/repo.git"
        # GIT_WORK_TREE must be set on server, I don't know why
        export GIT_WORK_TREE="${HOME}"
    else
        unset GIT_DIR
        unset GIT_WORK_TREE
    fi
}
add-zsh-hook -Uz chpwd() {env_on_chdir}
# stupid fix for 'git clone'
function paru {
    cd /tmp
    command paru "$@"
    cd - >/dev/null
}

# Make compinit automatically find new executables in the $PATH
# On-demand rehash
zshcache_time="$(date +%s%N)"
autoload -Uz add-zsh-hook
rehash_precmd() {
    if [[ -a /var/cache/zsh/pacman ]]; then
        local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
        if (( zshcache_time < paccache_time )); then
            rehash
            zshcache_time="$paccache_time"
        fi
    fi
}
add-zsh-hook -Uz precmd rehash_precmd
