#!/usr/bin/env python3
# yadm clone --bare --single-branch --branch <branch> <url>
# Make sure some programs are installed and force a checkout
from distro import name
from platform import system
from shutil import which
from subprocess import run, DEVNULL
from os import environ, getuid
from os.path import join, expanduser


def get_sudo_cmd():
    uid = getuid()
    if uid != 0:
        return ["sudo"]
    else:
        return []


def check_os():
    err_msg = "This script currently doesn't support OS other than Arch Linux"
    if system() != "Linux":
        raise SystemExit(err_msg)
    else:
        if name() != "Arch Linux":
            raise SystemExit(err_msg)
        else:
            return


def check_paru(sudo_cmd):
    if which("paru") is None:
        run([*sudo_cmd, "pacman", "-Syu", "--needed", "base-devel"], check=True)
        dir = environ["TMPDIR"]
        run(
            ["git", "clone", "https://aur.archlinux.org/paru.git"],
            cwd=dir,
            check=True,
        )
        run(["makepkg", "-si"], cwd=join(dir, "paru"), check=True)
        print()
    else:
        return


def install_common(sudo_cmd):
    packages = {
        "kitty-terminfo",
        "zoxide",
        "fzf",
        "zsh",
        "zsh-completions",
        "zsh-history-substring-search",
        "zsh-syntax-highlighting",
        "zsh-theme-powerlevel10k-git",
        "zsh-autosuggestions",
        "fd",
        "ripgrep",
        "trash-cli",
        "neovim",
        "python-pynvim",
        "duf",
        "dust",
        "pkgfile",
    }
    if sudo_cmd != []:
        run(["paru", "-Syu", "--needed", *packages], check=True)
        print()
    else:
        aur_package = "zsh-theme-powerlevel10k-git"
        packages.discard(aur_package)

        run(["pacman", "-Syu", "--needed", *packages], check=True)
        if (
            run(
                ["pacman", "-Q", aur_package], stdout=DEVNULL, stderr=DEVNULL
            ).returncode
            != 0
        ):
            print(f"`{aur_package}` is not installed")
            print()
        else:
            return


def set_worktree():
    run(["yadm", "config", "core.worktree", expanduser("~")], check=True)


def hide_untracked():
    run(["yadm", "config", "status.showUntrackedFiles", "no"], check=True)


def validate_upstream_branch(branch):
    returncode = run(
        ["yadm", "config", "--get", "remote.origin.fetch"],
        stdout=DEVNULL,
        stderr=DEVNULL,
    ).returncode
    if returncode != 0:
        run(["yadm", "remote", "set-branches", "origin", branch], check=True)
    else:
        return


def force_checkout(branch):
    run(["yadm", "status"], check=True)
    print()

    want_checkout = input(":: Do you want to force the checkout? [y/N] ")
    if want_checkout in {"y", "Y"}:
        run(["yadm", "checkout", "-f", branch], check=True)
        print()
    elif want_checkout in {"n", "N", ""}:
        return
    else:
        raise SystemExit("Invalid parameter")


def update_submodule():
    has_submodule = run(
        ["yadm", "submodule", "status"], check=True, capture_output=True, text=True
    ).stdout.rstrip()
    if has_submodule != "":
        run(
            ["yadm", "submodule", "update", "--init", "--recursive", "--remote"],
            check=True,
        )
        print()
    else:
        return


def install_for_main(sudo_cmd):
    run([*sudo_cmd, "pacman", "-Syu", "--needed", "kitty"], check=True)

    want_lf_installed = input(":: Install lf? [Y/n] ")
    if want_lf_installed in {"y", "Y", ""}:
        run(
            [
                *sudo_cmd,
                "pacman",
                "-Syu",
                "--needed",
                "lf",
                "ffmpegthumbnailer",
                "atool",
            ],
            check=True,
        )
        print()
    elif want_lf_installed in {"n", "N"}:
        return
    else:
        raise SystemExit("Invalid parameter")


def main():
    check_os()
    set_worktree()
    hide_untracked()

    branch = run(
        ["yadm", "branch", "--show-current"], capture_output=True, text=True, check=True
    ).stdout.rstrip()
    validate_upstream_branch(branch)
    force_checkout(branch)

    update_submodule()

    sudo_cmd = get_sudo_cmd()
    check_paru(sudo_cmd)
    install_common(sudo_cmd)
    if branch == "main":
        install_for_main(sudo_cmd)
    else:
        return


if __name__ == "__main__":
    main()
