#!/usr/bin/env bash
file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

filetype="$(mime "${file}")"
export filetype

if [[ "$filetype" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" </dev/null >/dev/tty
    exit 1 #to clear the last displayed image, no idea on why we need do this
elif [[ "$filetype" =~ ^video ]]; then
    # Inspired by the following program
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(thumb.py "$file")" </dev/null >/dev/tty
    exit 1
elif [[ "$filetype" =~ ^audio ]] && (mediainfo "$file" | rg -q -m 1 'Cover'); then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(thumb.py "$file")" </dev/null >/dev/tty
    exit 1
else
    ~/.config/ranger/scope.sh "$file"
fi
