[manager]
sort_by = "mtime"
sort_dir_first = true
sort_reverse = true

[preview]
image_filter = "lanczos3"
image_delay = 0

[tasks]
image_alloc = 0
image_bound = [0, 0]
suppress_preload = true

[plugin]
prepend_preloaders = [
    { mime = "audio/*", run = "audio" },
    { name = "*.m4a", run = "audio" },
]

prepend_previewers = [
    { mime = "audio/*", run = "audio" },
    { name = "*.m4a", run = "audio" },

    { mime = "text/*", run = "bat" },
    { mime = "application/json", run = "bat" },
    { mime = "*/{xml,javascript,wine-extension-ini}", run = "bat" },
]

[which]

[opener]
play = [
    { run = 'mpv "$@"', block = true, for = "unix" },
    { run = 'mpv "%1"', for = "windows" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
